in_channels: 3
num_classes: 2
band_num: [4, 6, 7]   # band select
height: 400 
width: 400
model_name: unet
batch_size: 10
epochs: 500
learning_rate: !!float 3e-4
val_plot_epoch: 5
augment: False
transfer_lr: False
gpu: !!str 3
trainOn: all
experiment: Band467
patchify: True
patch_class_balance: True
patch_size: 256
stride: 64
p_train_dir: json/train_patch_phr_cb_256.json
p_valid_dir: json/valid_patch_phr_cb_256.json
p_test_dir: json/test_patch_phr_cb_256.json
p_eval_dir: json/eval_patch_phr_cb_256.json
weights: False
balance_weights: [1.8, 8.2]
dataset_dir: /mnt/hdd2/mdsamiul/multispectral/data/
root_dir: /mnt/hdd2/mdsamiul/multispectral/
train_size: 0.8
train_dir: train.csv
valid_dir: valid.csv
test_dir: test.csv
eval_dir: eval.csv
csv: True
val_pred_plot: True
lr: True
tensorboard: True
early_stop: False
checkpoint: True
patience: 300
load_model_name: m.hdf5
load_model_dir: None
evaluation: False
video_path: None
plot_single: False
index: -1
